[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin=lib/openzeppelin-contracts',
    '@uniswap/v3-core/=lib/uniswap-v3-core',
    '@uniswap/v3-periphery/=lib/uniswap-v3-periphery',
    'forge-std/=lib/forge-std/src/',
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config